# Generated by Django 5.1.7 on 2025-04-15 06:15

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_created_at_vehicle_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_rc',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_back_image',
            field=models.ImageField(null=True, upload_to=vehicle.models.unique_vehicle_images_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_chassis_number',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_engine_number',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_front_image',
            field=models.ImageField(null=True, upload_to=vehicle.models.unique_vehicle_images_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_leftSide_image',
            field=models.ImageField(null=True, upload_to=vehicle.models.unique_vehicle_images_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_rc_back',
            field=models.ImageField(null=True, upload_to=vehicle.models.unique_vehicle_rcimage_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_rc_front',
            field=models.ImageField(null=True, upload_to=vehicle.models.unique_vehicle_rcimage_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_rightSide_image',
            field=models.ImageField(null=True, upload_to=vehicle.models.unique_vehicle_images_path),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
