# Generated by Django 5.1.7 on 2025-04-15 06:20

import django.db.models.deletion
import django.utils.timezone
import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_driverrequest_action_at'),
        ('vehicle', '0003_remove_vehicle_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_front_image', models.ImageField(upload_to=vehicle.models.unique_vehicle_images_path)),
                ('vehicle_back_image', models.ImageField(upload_to=vehicle.models.unique_vehicle_images_path)),
                ('vehicle_leftSide_image', models.ImageField(upload_to=vehicle.models.unique_vehicle_images_path)),
                ('vehicle_rightSide_image', models.ImageField(upload_to=vehicle.models.unique_vehicle_images_path)),
                ('vehicle_number', models.CharField(max_length=8, unique=True)),
                ('vehicle_rc_front_image', models.ImageField(upload_to=vehicle.models.unique_vehicle_rcimage_path)),
                ('vehicle_rc_back_image', models.ImageField(upload_to=vehicle.models.unique_vehicle_rcimage_path)),
                ('vehicle_type', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driverdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
