# Generated by Django 5.1.7 on 2025-04-15 09:02

import django.db.models.deletion
import django.utils.timezone
import vehicle.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicle_vehicle_back_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(max_length=100, unique=True)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to=vehicle.models.unique_vehicle_images_path)),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_size', models.IntegerField(blank=True, null=True)),
                ('document_mime_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_back_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_front_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_leftSide_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_rc_back',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_rc_front',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_rightSide_image',
        ),
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='vehicle_back_image',
        ),
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='vehicle_front_image',
        ),
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='vehicle_leftSide_image',
        ),
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='vehicle_rc_back_image',
        ),
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='vehicle_rc_front_image',
        ),
        migrations.RemoveField(
            model_name='vehiclerequest',
            name='vehicle_rightSide_image',
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_request_verifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='verification_documents',
            field=models.ManyToManyField(related_name='vehicle_approve_documents', to='vehicle.documenttype'),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='verification_documents',
            field=models.ManyToManyField(related_name='vehicle_request_documents', to='vehicle.documenttype'),
        ),
    ]
