# Generated by Django 5.1.7 on 2025-04-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_documenttype_remove_vehicle_vehicle_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequest',
            name='vehicle_chassis_number',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiclerequest',
            name='vehicle_engine_number',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
