# Generated by Django 5.1.7 on 2025-04-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehiclerequest_vehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
