# Generated by Django 5.1.7 on 2025-04-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_vehicle_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerequest',
            name='vehicle_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
