# Generated by Django 5.1.7 on 2025-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_vehiclerequest_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
    ]
