# Generated by Django 5.1.7 on 2025-04-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_alter_documenttype_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('2 Wheeler', '2 Wheeler'), ('3 Wheeler', '3 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiclerequest',
            name='vehicle_type',
            field=models.CharField(choices=[('2 Wheeler', '2 Wheeler'), ('3 Wheeler', '3 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=10),
        ),
    ]
