# Generated by Django 5.1.7 on 2025-03-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_documentrequired_driverdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='verification_documents',
            field=models.ManyToManyField(related_name='driver_details', to='user.documentrequired'),
        ),
    ]
