# Generated by Django 5.1.7 on 2025-03-31 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_key', models.CharField(max_length=50)),
                ('document_label', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('field_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
