# Generated by Django 5.1.7 on 2025-04-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_documentrequired_document_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPermission',
            new_name='RolePermission',
        ),
    ]
