# Generated by Django 5.1.7 on 2025-04-09 05:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_adminpermission_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdetail',
            name='lang',
            field=models.ManyToManyField(related_name='driver_details_lang', to='user.language'),
        ),
        migrations.AlterField(
            model_name='driverdetail',
            name='verification_documents',
            field=models.ManyToManyField(related_name='driver_detail_documents', to='user.documentrequired'),
        ),
        migrations.CreateModel(
            name='DriverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('lang', models.ManyToManyField(related_name='driver_request_lang', to='user.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_request_user', to=settings.AUTH_USER_MODEL)),
                ('verification_documents', models.ManyToManyField(related_name='driver_request_documents', to='user.documentrequired')),
                ('verifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_request_verifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
