# Generated by Django 5.1.7 on 2025-04-09 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_driverdetail_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='verifier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_request_verifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
