# Generated by Django 5.1.7 on 2025-04-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_driverrequest_verifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdetail',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='driverdetail',
            name='status',
        ),
    ]
