# Generated by Django 5.1.7 on 2025-04-09 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_driverdetail_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverrequest',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_request_verifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
