# Generated by Django 5.1.7 on 2025-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_driverrequest_action_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverrequest',
            name='action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
