# Generated by Django 5.1.7 on 2025-04-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
