# Generated by Django 5.1.7 on 2025-04-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_address_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='drop_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True),
        ),
    ]
