# Generated by Django 5.1.7 on 2025-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_trip_drop_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='drop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
