# Generated by Django 5.1.7 on 2025-04-29 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_trip_drop_time_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('normal_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('night_time_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peak_time_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('night_time_starting', models.TimeField()),
                ('night_time_ending', models.TimeField()),
                ('peak_time_morning_starting', models.TimeField()),
                ('peak_time_morning_ending', models.TimeField()),
                ('peak_time_evening_starting', models.TimeField()),
                ('peak_time_evening_ending', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
