# Generated by Django 5.1.7 on 2025-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_tripfares_alter_trip_driver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TripFares',
            new_name='TripFare',
        ),
    ]
