# Generated by Django 5.1.7 on 2025-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_trip_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('2 Wheeler', '2 Wheeler'), ('3 Wheeler', '3 Wheeler'), ('4 Wheeler', '4 Wheeler')], max_length=10, null=True),
        ),
    ]
