# Generated by Django 5.1.7 on 2025-05-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_trip_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverdetail',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
