# Generated by Django 5.1.7 on 2025-05-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_driverdetail_is_active_driverdetail_last_active_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdetail',
            old_name='is_active',
            new_name='is_online',
        ),
        migrations.RenameField(
            model_name='driverdetail',
            old_name='last_active_at',
            new_name='last_online_at',
        ),
    ]
