# Generated by Django 5.1.7 on 2025-05-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_rename_is_active_driverdetail_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('driver', 'Driver'), ('auto', 'Auto')], max_length=20, null=True),
        ),
    ]
