# Generated by Django 5.1.7 on 2025-05-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_trip_otp_alter_trip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='cancelation_description',
        ),
    ]
