# Generated by Django 5.1.7 on 2025-05-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_rename_description_trip_cancelation_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='rating',
            new_name='customer_rating',
        ),
        migrations.AddField(
            model_name='trip',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
